### ISSUE TITLE
settings-menuen for qlr-browser

### ISSUE THREAD

**Issue by gis-haderslev** [Septima/qgis-qlrbrowser#1]
Kan ikke finde menuen for QLR-browser. Kan vi få skærmdump?
Har prøvet det på QGIS 2.12 Lyon

**Comment by AsgerPetersen** [comment]
![image](https://cloud.githubusercontent.com/assets/1392735/11468318/d4f5a7c0-974e-11e5-9c72-def014c342d5.png)

Når pluginnet er aktiveret skulle der gerne komme et menupunkt under "Plugins", som hedder "Qlr Browser".

**Comment by gis-haderslev** [comment]
Har lige unpacked pluginet under flere QGIS versioner (forskellige PC maskiner)
2.8  Wien - virker ikke
2.10 Pisa - virker
2.12 - viser pluginet, men viser ikke filbrowseren, vises hellere ikke under plugins

**Comment by AsgerPetersen** [comment]
Spøjst! Jeg kigger på det med det samme.

_Asger Sigurd Skovbo Petersen_
Partner, Seniorkonsulent
asger@septima.dk

## Tlf +45 9132 6944

Septima P/S
Frederiksberggade (Strøget) 28 2. tv.
1459 Kbh K
www.septima.dk
Tlf +45 7230 0672
Cvr 34 900 841

2015-11-30 10:56 GMT+01:00 Nicolai - GIS Haderslev <notifications@github.com

**Comment by rastermanden** [comment]
I've added at [Test matrix](https://github.com/Septima/qgis-qlrbrowser/edit/master/README.md) to keep track of tests in different versions of QGIS against different operating systems.

**Comment by AsgerPetersen** [comment]
Jeg har testet i
2.12.0 windows 64bit, 2.12.1 windows 64bit og 2.12.0 mac 64 bit, og det virker alle steder.

Har du mulighed for at installere pluginnet "First Aid", genstarte QGIS og prøve en gang til? First Aid giver nogle meget nyttige fejlbeskeder, hvis der er python-kode, som fejler.

**Comment by gis-haderslev** [comment]
Hej igen.
Jeg har installeret FirstAid og har genstartet QGIS - så kommer værktøjet som det skal. Mærkelig.
Og jeg er sikkert jeg har genstartet QGIS også sidste gang, efter jeg har pakket pluginet ud.
Skal jeg teste på 2.8 eller dropper vi de tidligere versioner.

**Comment by AsgerPetersen** [comment]
Kan du prøve at slette base directory stien under settings og genstarte QGIS. Måske holder det så op med at virke igen. 

Det KAN nemlig være, at det bare tager lang tid for pluginnet at starte op, når der ikke er konfigureret en sti. I det tilfælde skal vi måske gøre noget specielt.

**Comment by gis-haderslev** [comment]
(QGIS 2.12.0 Lyon) 
Har gjort det. Ingen problemer.

**Comment by AsgerPetersen** [comment]
Jeg tror, vi lukker sagen her. Prøv meget gerne på en anden maskine og genåbn dette issue, hvis problemet dukker op igen.
