### ISSUE TITLE
Disable checkbox on some dirs

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/qgis-qlrbrowser#14]
Dirs with many layers should maybe not have a checkbox.

**Comment by gis-haderslev** [comment]
Maybe like a general option for all dirs under settings: 
on/off - checkbox on dirs

**Comment by Frederikssund** [comment]
It might be a setting for a "switch off checkbox" number under options. 
0 - never show checkbox; 
100000 (whatever) - Always show checkbox.
And with a default in the vicinity of 10

**Comment by AsgerPetersen** [comment]
Hey hey, hold your horses :-) So far I have not found a way to prevent the tree from showing checkboxes on _some_ items only.

I can switch checkboxes off or on, but not do it selectively. For now - that is.

**Comment by Frederikssund** [comment]
A question: The meaning with the 'directory' checkbox is to open (or close) every qlr file in the directory ?
Second question: If the answer for first question is yes: Will the checkbox control the behaviour of child directories ??

**Comment by AsgerPetersen** [comment]
@Frederikssund We need to figure that out before I can implement it. I think it is coming in the next iteration.

For now I am just trying to find a way to disable checkboxes on dirs. It seems it is not possible to remove the checkbox on some items without removing them on all items :-/ It is possible to prevent the user from actually checking specific boxes.
