### ISSUE TITLE
Plugin crashes on first edit of base path

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/qgis-qlrbrowser#16]
Probably path is `None` when first installed.

**Comment by gis-haderslev** [comment]
There are error on all attempting to **edit** base path and as consequence crashes connection between layers panel and qlr-browser :
removing layer  from layers panel does not  remove  checkbox X-mark.
and
removing checkbox X-mark does not remove layer from layers panel.

**Comment by AsgerPetersen** [comment]
Crash on (not first) edit of basepath:
![image](https://cloud.githubusercontent.com/assets/1392735/12578857/d41ee12a-c423-11e5-9b0e-b98d77bb1760.png)
