### ISSUE TITLE
Crash when deleting a qlr file

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/qgis-qlrbrowser#18]
Possibly only when qlr-file is used...

**Comment by AsgerPetersen** [comment]
@MieWinstrup are you able to reproduce this? I can't.

**Comment by AsgerPetersen** [comment]
@MieWinstrup ?

**Comment by MieWinstrup** [comment]
I get the attached error message if a qlr file in the folder is deleted while QGIS with the qlr-browser is open. However, if QIS is closed and then reopened the deleted layer is removed from the qlr-browser it works fine.

![error_qlr_when_deleting](https://cloud.githubusercontent.com/assets/16276034/12779552/c6f19e16-ca68-11e5-995c-5ff6a1879d79.png)

**Comment by Frederikssund** [comment]
A check with "os.path.isfile(qlrpath)" might solve the problem

**Comment by AsgerPetersen** [comment]
Now, when the user checks a qlr which no longer exist we show a warning message like "Error: The selected path no longer exists" and then we force the qlr browser to update its file tree
