### ISSUE TITLE
Decision needed: Future location of the code

### ISSUE THREAD

**Issue by MieWinstrup** [Septima/qgis-qlrbrowser#19]
@Haderslev Kommune and Frederikssund Kommune:  
Currently the code to the qlr-plugin is saved in Septima's GItHub, but where do you want the code stored in the future? 

There are (at least) two possibilities:
1: Stored in Septimas GItHub (as it is now)
2: Stored in your own GitHub

What do you prefer?

**Comment by gis-haderslev** [comment]
I will prefer Septimas GItHub. Vi kan anytime download the code if it is nessesary.

**Comment by Frederikssund** [comment]
Leave it in Septima's part of GitHub. As long the repository remains public
Regards Bo Victor

**Comment by MieWinstrup** [comment]
Ok, thanks for the fast reply.
