### ISSUE TITLE
Decision needed: Do you want the qlr-browser to be available in the QGIS official repository?

### ISSUE THREAD

**Issue by MieWinstrup** [Septima/qgis-qlrbrowser#20]
@Haderslev Kommune and Frederikssund Kommune:

Do you want the Qlr-browser to be available in the QGIS official repository?

If you want this, then do you want the 'trin 1 final'-version (where the rest of the errors are corrected) to be uploaded or do you want to wait with the upload until the final-final-version (after trin 3)?

**Comment by AsgerPetersen** [comment]
Bonus question: Would you like us to use the Septima account on qgis plugin repository to administrate the plugin, or would you like to have a dedicated account?

**Comment by Frederikssund** [comment]
1) Yes, If possible, the plugin should be a part of the official QGIS repository
2) Upload after the 'trin 1 final' version is done. That will give us more eyeballs on the plugin for finding and correcting errors. A maybe some intelligent suggestions for improvements (you'll never know !)
3) Use the Septima account. (I have enough accounts to worry about, I don't need another one ;-)

**Comment by gis-haderslev** [comment]
Totally agree with Frederikssund

**Comment by MieWinstrup** [comment]
Ok. The plugin will be uploaded to the official QGIS repository when the 'trin 1 final' version is done and we will use the Septima account.
