### ISSUE TITLE
removal of suffix works incorrect if file name contains more than one period (.)

### ISSUE THREAD

**Issue by Frederikssund** [Septima/qgis-qlrbrowser#21]
If you have a file called "Yummy.qlr" it will show as "Yummy" in the browser. This is as it should be.
If you have a file called "**.**Doh.qlr" it will be shown as a line in the browser without any name (The mouse-over works though) 
The error is how the plugin removes the suffix ".qlr" from the individual filenames. It searches for periods in the filename from "left-to-right". It should be searching from "right-to-left"

**Comment by AsgerPetersen** [comment]
Hmm, `QFileInfo(file).baseName()` does this.

I guess we will have to roll our own `basename` function then.

**Comment by Frederikssund** [comment]
What about changing "QFileInfo(file).baseName()"
to "QFileInfo(file).completeBaseName()" ?

See: http://doc.qt.io/qt-4.8/qfileinfo.html#completeBaseName

(and is it possible for you to get the fix into 0.20 before uploading it to qgis official ?? )

**Comment by AsgerPetersen** [comment]
Aaaah, I didn't notice that function. It should of course be that one!

The 0.2.0 package has been uploaded, so it is too late to include it. But
it is not a big problem to upload a v0.2.1 later this week :-)

_Asger Sigurd Skovbo Petersen_
Partner, Seniorkonsulent
asger@septima.dk

## Tlf +45 9132 6944

Septima P/S
Frederiksberggade (Strøget) 28 2. tv.
1459 Kbh K
www.septima.dk
Tlf +45 7230 0672
Cvr 34 900 841

2016-02-03 14:51 GMT+01:00 Frederikssund Kommune notifications@github.com:

**Comment by Frederikssund** [comment]
That's okay ;-)
