### ISSUE TITLE
User setting for ordering af qlr - files in browser tree (nice to have)

### ISSUE THREAD

**Issue by Frederikssund** [Septima/qgis-qlrbrowser#22]
It would be nice if it was possible to make the ordering of qlr-filenames in the browser tree a user selectable option. Like with these 4 options.
1. ascending by filename
2. descending by filename
3. ascending by file update-datetime
4. descending by file update-datetime

This would make it possible to ex. manipulate the name order in the browser tree by changing the file-times on the individual files.    

On second thought: There should be a additional user selectable option for the ordering of the _directories_ with the 4 same options as for the files

**Comment by Frederikssund** [comment]
Make a global setting :  **QLRFILESORTORDER**, which is switchable to one of the following values:

QLRFILESORTORDER = QDir.Name
QLRFILESORTORDER = QDir.Name | QDir.Reversed
QLRFILESORTORDER = QDir.Time
QLRFILESORTORDER = QDir.Time | QDir.Reversed

filesystemmodel.py, line 53 change to:
`for finfo in qdir.entryInfoList( FileSystemItem.fileExtensions , QDir.Files | QDir.AllDirs | QDir.NoDotAndDotDot,QLRFILESORTORDER):
`

**Comment by Frederikssund** [comment]
Close this one. Solution suggested in #43 is better.

**Comment by MieWinstrup** [comment]
Issue closed as requested by @Frederikssund
