### ISSUE TITLE
Items should not be selectable

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/qgis-qlrbrowser#23]
I think it doesnt make sense that the items in the browser are selectable. The selection doesnt mean anything.

On the dump below what does it mean that `keyw` is selected?
![image](https://cloud.githubusercontent.com/assets/1392735/12777604/3686c220-ca5e-11e5-9c2a-83f864518a1b.png)

**Comment by Frederikssund** [comment]
Understood, and you're right. It doesn't make sense.
