### ISSUE TITLE
Activation  of the plugin hangs qgis

### ISSUE THREAD

**Issue by pcav** [Septima/qgis-qlrbrowser#27]
Once installed, the plugin is inactive. Activating it trough the plugin manager causes the system to swap, and becoming unresponsive (Debian Sid).
I'm unpublishing the plugin until the problem will be solved, as it may cause trouble to many users.
Sorry about that.

**Comment by AsgerPetersen** [comment]
Hi @pcav thank you very much for reporting this. I am sorry you had to waste time on a non-functional plugin.

The issue probably is that we use the users home dir as a default root path of our qlr tree browser. And your home dir is probably larger than any tested so far.

It is too bad if we can't give the user a reasonable default setting of the root path, but maybe we will just have to write "No root path configured" in the tree until the user has explicitly configured a meaningful path.

**Comment by AsgerPetersen** [comment]
@Frederikssund @gis-haderslev I will try to fix this bug today unless you disagree.

**Comment by pcav** [comment]
Thanks for the explanation. Yes, I have a big /home.
Perhaps a popup at first activation, asking to set up a path would be good?
Anyway, the system should not hang if the user selects a too big dir.

**Comment by gis-haderslev** [comment]
Fine if you can fix it. Popup "No root path configured", which is asking to set up a path, sounds good.

**Comment by Frederikssund** [comment]
Ok - late to the party, but the fix is ok for me / bvtho frederikssund (And sorry for suggesting the home dir as a default value in the first place. I didn't think it though)

**Comment by AsgerPetersen** [comment]
@pcav I think the new version uploaded yesterday should fix the problem.

**Comment by pcav** [comment]
I cannot confirm. Still same problem here.

**Comment by pcav** [comment]
Please reopen this - temporarily unapproving the plugin.

**Comment by AsgerPetersen** [comment]
@pcav Ah, as you already have a configuration for the plugin (which unfortunately configures HOME as the base path) you are not presented with the new feature. And your QGIS still hangs.

I think this shows us, that we also need to protect the user from manually selecting a very large base directory which will hang QGIS.

Hopefully the NEXT version will be really good :-)

**Comment by pcav** [comment]
Looking forward to it :)

**Comment by NathanW2** [comment]
@AsgerPetersen looking at your implementation.  I think you need to thread it to get any UI result from a large folder without a new thread you are always going to block looking for files.

**Comment by AsgerPetersen** [comment]
@NathanW2 Thank you very much for looking at our code!

So far we have only considered the use case where the plugin is pointing at a very shallow folder structure. Something like 100 qlr files sorted in some folders. In that case the plugin is only blocking for a very limited time while traversing the folder structure. We did not imagine the plugin being used as a "regular" file browser.

An async implementation of the file system code would be a very nice addition. And it would certainly improve the usability of the plugin.

**Comment by pcav** [comment]
The problem is that the issue surfaces upon activation of the plugin, before the user has an opportunity to choose any directory.

**Comment by Frederikssund** [comment]
@AsgerPetersen: Could you give me a quote on implementing a simple directory/file counter that would stop the directory/file traversing after a specific, userdefined number of files traversed ? And having a sane default value (100 ? 1000 ? 10000 ?) 
And I agree with you and NathanW, that an async implementation of the file traversing would be a nice addition (next version perhaps ?)

**Comment by NathanW2** [comment]
I can have a crack at a threaded version on the train in the morning for
you.

**Comment by AsgerPetersen** [comment]
@Frederikssund I have already implemented code doing exactly that. It breaks after reading 1000 file items.

@NathanW2 That is very kind of you! If you think this plugin is interesting, maybe I could convince you to have a look at something else which is making the plugin a bit shaky: Loading a qlr file using `QgsLayerDefinition.loadLayerDefinition` doesn't return a handle to the loaded node. To get a hold of the loaded node I hook in to `layerTreeRoot.addedChildren`. This approach is not fail safe and it feels a little dirty. See https://github.com/Septima/qgis-qlrbrowser/blob/2637ad389e085769bf193b93480e2b1db2147382/src/QlrBrowser/core/qlrmanager.py#L120-L129 and https://github.com/Septima/qgis-qlrbrowser/blob/2637ad389e085769bf193b93480e2b1db2147382/src/QlrBrowser/core/qlrmanager.py#L72-L75 Are there other, more robust ways to achieve the same effect?

**Comment by NathanW2** [comment]
@AsgerPetersen I don't suspect so as the ids are changed when loaded.  I assume you want this so that you can turn stuff on and off?

**Comment by AsgerPetersen** [comment]
@NathanW2 Exactly! It is used to keep qlr browser and QGIS legend in sync. I have created a new issue #29 for this particular issue. Just to keep issues separated.
