### ISSUE TITLE
More robust way to get handle of loaded layer(s)

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/qgis-qlrbrowser#29]
(Continued from #27)

Loading a qlr file using `QgsLayerDefinition.loadLayerDefinition` doesn't return a handle to the loaded node. To get a hold of the loaded node I hook in to layerTreeRoot.addedChildren. This approach is not fail safe and it feels a little dirty. See https://github.com/Septima/qgis-qlrbrowser/blob/2637ad389e085769bf193b93480e2b1db2147382/src/QlrBrowser/core/qlrmanager.py#L120-L129 and https://github.com/Septima/qgis-qlrbrowser/blob/2637ad389e085769bf193b93480e2b1db2147382/src/QlrBrowser/core/qlrmanager.py#L72-L75

The handle is used to keep qlr browser and QGIS legend in sync. Ie remove a layer from the QGIS legend if it is unchecked in qlr browser and unchecking a qlr in qlr browser if the layer is removed from the legend.

**Comment by NathanW2** [comment]
Have an idea.  There is nothing to say the `rootGroup` you pass into `loadLayerDefinition` has to be the project group.  

Make a new stub group

``` python
group = QgsLayerTreeGroup()
QgsLayerDefinition.loadLayerDefinition(path, group)
# Get the layer ids from the group we made
layers = group.findLayerIds()
# Get a list of nodes
nodes = group.children()
# Insert them into the main project
QgsProject.instance().layerTreeGroup().insertChildNodes(-1, nodes)
```

**Comment by NathanW2** [comment]
In fact if you look at the code for `loadLayerDefinition` it's doing that anyway so we are just changing the root and readding into the project our self.

**Comment by AsgerPetersen** [comment]
Good idea! That would also make life easier with regards to controlling where the loaded layers end up in the legend. Thank you!

**Comment by NathanW2** [comment]
Bingo :)

**Comment by bsnizek** [comment]
See merge request.

**Comment by AsgerPetersen** [comment]
After a lot of QGIS crashes (SIGSEGV) I found out that Nathans code needs to be tweaked a bit.

Nodes added to `QgsProject.instance().layerTreeGroup()` are not allowed to be part of an existing tree (=cannot have a parent) as also stated in the [documentation](http://qgis.org/api/classQgsLayerTreeGroup.html). 

So changing Nathans code to:

``` python
group = QgsLayerTreeGroup()
QgsLayerDefinition.loadLayerDefinition(path, group)
# Get a list of nodes
nodes = group.children()
# Remove from parent node
for n in nodes:
    group.takeChild(n)
# Insert them into the main project
QgsProject.instance().layerTreeGroup().insertChildNodes(0, nodes)
```

This seems to solve the problem.
