### ISSUE TITLE
Search function is somewhat stupid :-)

### ISSUE THREAD

**Issue by Frederikssund** [Septima/qgis-qlrbrowser#30]
**The scenario**: I have a directory called "Nature Stuff". This directory contains a lot of qlr-files, where _none_ of the individual qlr-files has names containing "Nature" but obviously defines layers associated with "Nature Stuff" (hence the directory name) 

**The problem**: If I use the seach function and write "Nature", the function will find the _directory_ called "Nature Stuff", but it will be empty, because the filter function has removed all the qlr-files _in_ the directory (the filenames didn't contain "Nature") 

**The solution**: The filter function should stop filtering on directories with names that satisfy the search criteria.

**Comment by AsgerPetersen** [comment]
That does sound a bit.... sub optimal :-)

So, how _should_ directory filtering work?

When a directory name matches the filter all files directly under this directory should be included in the result. How about sub directories? Should they also be included?

**Comment by Frederikssund** [comment]
"Sub optimal" has a nice ring to it  ;-) . 

I would say "yes" regarding the sub-dirs: When the search function encounters a directory which satisfies the filter expression, all files and sub-dirs in the directory (plus the contents in the sub-dirs) should be included in the search result.
