### ISSUE TITLE
Async file system traversal

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/qgis-qlrbrowser#31]
As discussed in #27 a threaded version of the file system recursion would improve the plugin.

Could be done like http://snorf.net/blog/2013/12/07/multithreading-in-qgis-python-plugins/

Edit 2020-12-07: Or maybe using a more recent technology https://docs.qgis.org/3.16/en/docs/pyqgis_developer_cookbook/tasks.html

**Comment by MieWinstrup** [comment]
Implemented with plugin [version 3.0.0](https://github.com/Septima/qgis-qlrbrowser/releases/tag/v.3.0.0)
