### ISSUE TITLE
Max recursion depth as setting

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/qgis-qlrbrowser#32]
Get value from plugin setting so it can be viewed and set at the project vars viewer

**Comment by bsnizek** [comment]
Settings are written and read but cannot be seen in the Project Properties | Variables dialog. Any ideas ?

**Comment by AsgerPetersen** [comment]
The settings module has some sort of scope indication for each setting.
Might be that

On Wednesday, 9 March 2016, Bernhard Snizek notifications@github.com
wrote:

> Settings are written and read but cannot be seen in the Project Properties
> | Variables dialog. Any ideas ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Septima/qgis-qlrbrowser/issues/32#issuecomment-194384050
> .

## 

_Asger Sigurd Skovbo Petersen_
Partner, Seniorkonsulent
asger@septima.dk

## Tlf +45 9132 6944

Septima P/S
Frederiksberggade (Strøget) 28 2. tv.
1459 Kbh K
www.septima.dk
Tlf +45 7230 0672
Cvr 34 900 841

**Comment by bsnizek** [comment]
I have been trying this for some time and cannot get it to work.

I have tried both this approach:

http://docs.qgis.org/testing/en/docs/pyqgis_developer_cookbook/settings.html

and this:

   http://3nids.github.io/qgissettingmanager/

The latter is already implemented in the product - a baseDirectory in the global settings is defined but this  is not shown in the variables doc. 

Can we look at this together on Monday ?

**Comment by AsgerPetersen** [comment]
This is how it is done i Geosearch DK

``` python
    def updateconfig(self):
        s = QSettings()
        k = __package__
        s.setValue(k + "/username",     self.config['username'])
        s.setValue(k + "/password",     self.config['password'])
        s.setValue(k + "/resources",    self.config['resources'])
        s.setValue(k + "/maxresults",   self.config['maxresults'])
        s.setValue(k + "/callback",     self.config['callback'])
        s.setValue(k + "/muncodes",     self.config['muncodes'])
```

It shows up as 
![image](https://cloud.githubusercontent.com/assets/1392735/13700882/012699b4-e784-11e5-840d-1d0bafda332e.png)

It _seems_ to be basically the same approach used by qgissettingsmanager. It is implemented per type in `qgissettingsmanager/types/TYPENAME.py`. For strings:

``` python
[...]
setGlobal = lambda(value): QSettings(pluginName, pluginName).setValue(name, value)
[...]
```
