### ISSUE TITLE
Length of (sub)foldername

### ISSUE THREAD

**Issue by haderslev1algo** [Septima/qgis-qlrbrowser#34]
Just a tiny thing :-): Is it possible to define the length of subfoldername from 30 to 35 signs?
Otherwise the name, which is longer than 30 signs,  is cut off in Qlr Browser overview...
![udklip1](https://cloud.githubusercontent.com/assets/14937753/12973858/fc20657a-d0af-11e5-9732-c4b51c8963f6.PNG)
![unavngivet](https://cloud.githubusercontent.com/assets/14937753/12973931/64cde4ee-d0b0-11e5-9131-f86a5f78c788.png)

**Comment by Frederikssund** [comment]
Is this not a deriative of #37  ??  As far as I can see there is no limitation of the file or directory names in browser-tree widget. It's probably the bug with periods in the directory name that causes the error in the example

**Comment by Frederikssund** [comment]
Ok, just tried to create a long directory name: "**This is a very long name for a directory without any period**"
The browser showed all of the name, so this bug is simply a copy of #37

**Comment by bsnizek** [comment]
It works in the branch where we have fixed #37.

**Comment by bsnizek** [comment]
Works here too. I close it.
