### ISSUE TITLE
Wrong directory marker (bug)

### ISSUE THREAD

**Issue by Frederikssund** [Septima/qgis-qlrbrowser#35]
Scenario:  You have two directories in the qlr browser path: One called "**Powder**" and another called "**Powder and Cannon**".  If you click (activate) one ore more qlr files in directory "**Powder and Cannon**" then the directory name "**Powder and Cannon**" will be highlighted and the number of qlr files opened in the directory will be shown (as it should)

The error: However, the directory "**Powder**" wil be highlighted too. And the "file-counter" for directory "**Powder**" wil be counted up with the number of qlr files opened in directory "**Powder and Cannon**". 

The two directories contains a completly different set of qlr files and the layers in the qlr files is different too.

The error is only triggered when you open af qlr file in the directory with the longest name

It might have something to do with an internal string compare function that doesn't work as intended when you compare two directory-names, where one of the names is a true subset of the other name.

**Comment by bsnizek** [comment]
Fixed and committed to https://github.com/Septima/qgis-qlrbrowser/tree/bugfix-bernie-35

**Comment by bsnizek** [comment]
This works now - I'll close the issue.
