### ISSUE TITLE
Directory name get's truncated if name contains a period "." (bug)

### ISSUE THREAD

**Issue by Frederikssund** [Septima/qgis-qlrbrowser#37]
The issue: If a directory name contains a period, it wil be truncated with the rightmost part of the name removed.

Example: a directory name **"1.2.3 JUHU"** wil be represented in the qlr browser as **"1.2"**. However, the "hover" text  contains the correct filename.

**Comment by Frederikssund** [comment]
File: filesystemmodel.py, line 47 - change to:
`self.displayname = self.fileinfo.fileName() if self.fileinfo.isDir() else self.fileinfo.completeBaseName()`

Only cursory tested....

**Comment by bsnizek** [comment]
Fixed in branch: https://github.com/Septima/qgis-qlrbrowser/tree/bugfix-bernie-37

**Comment by bsnizek** [comment]
https://github.com/Septima/qgis-qlrbrowser/commit/48359faed763b114ec1ed521faf48344543c255a
