### ISSUE TITLE
User sort of qrl-files in display

### ISSUE THREAD

**Issue by ErlingKristensen** [Septima/qgis-qlrbrowser#43]
It would be nice to have an option (on/off) where it would be possible to hide the first 2 (left) characters from the qrl-filename displayed in the QGIS-browser. In this way you could name files starting with number 00 to 99 - and use the 2 first characters to define the display order in QRL-browser. We would as an example like to display "Lokalplan vedtaget" before "Lokalplan forelobig" this could be possible naming qrl-files: "01Lokalplan vetaget.qrl" and "02Lokalplan forelobig.qrl".

**Comment by AsgerPetersen** [comment]
Sorting qlr files in other ways than by file name is something we should consider. 

#22 is a related issue.

**Comment by Frederikssund** [comment]
I think, this is an excellent solution for the problem on how to sort qlr files other than by a "strict" alphabetical sort. You could have a global setting with a number between for example: 0-3, and with the default of "0". You don't need a on/off switch, as the value "0" would have the meaning "off"

I'm not sure how to proceed: like #22 where you manipulate the sort order with the "time-modified" attribute for the qlr-files or this (#43) where you hide the first characters of a filename. 
- #22 : You need to know how to unix-"touch" a file so it gets a new specific "time-modified" value
- #43 : You need to rename all your qlr-files and prefix them with a number. 

Opinions ??

**Comment by AsgerPetersen** [comment]
I think sorting by file name is better than sorting by timestamp.

Consider having 15 files being sorted by time. Now assume you need to edit the qlr being sorted as number 7. After the edit you would have to touch a whole bunch of other files in the exact correct order to make the files sort correctly again. I think this not desirable.

Using file name sorting you would just edit the file and save it with the same file name and everything would sort as before.

**Comment by Frederikssund** [comment]
Yep, that was my (second) thought too. I'll think we should close #22 and proceed with @erlingkristensen's suggestion. I propose, that we'll have a global setting - Something like "Hide first n characters in file and directory names" with n having a value between 0 - 3. And use the alphabetic sort we have now, off course on the full names.

**Comment by AsgerPetersen** [comment]
What about hiding any number of numeric chars if they appear before a certain char. For instance
for `010_xxxx` 
we would show `xxx`,
for `1_xxx`we would show `xxx`
but for `010xxx` we would show `010xxx`.

I think this would be a pretty flexible approach. Being forced to always prefix all files with the same number of chars seems a little cumbersome.

We could then expose this options as a checkmark with a text like _"Hide numeric prefixes (formatted like: '01_' )"_

**Comment by Frederikssund** [comment]
Good suggestion @AsgerPetersen. No global setting, but a rule: 

"If a filename or directoryname contains an integer followed by an underscore ("123_xxx.." or "5432_yyy..") the integer and underscore will be removed from the the displayed name for the file or directory in the browser tree".

**Comment by ErlingKristensen** [comment]
Only a small comment: "If a filename or directoryname **starting** with an integer followed by . . . "

**Comment by AsgerPetersen** [comment]
Question: Is underscore "_" the best char for this purpose? We could also decide on another more seldomly used char. This would lower the chance of being hit by this feature by accident.

**Comment by Frederikssund** [comment]
"!#$%&'()+'-;=@[]^_`{}~" can all be used (It's actually a legal directory name in windows). I would suggest somthing like
-  [123]blahblah --> blahblah 
- 123~blahblah --> blahblah

All the characters in "!#$%&'()+'-;=@[]^_`{}~" is in the US ASCII table, som we shouldn't have any problems with that. 

Which "special" characters is not allowed (or have a special meaning) for file- and directory names in the Linux or Mac operatings systems??

**Comment by Frederikssund** [comment]
And maybe have a global setting to either:
- choose the special character from a list - or
- have a checkbox to toggle the function on/off

**Comment by bsnizek** [comment]
https://github.com/Septima/qgis-qlrbrowser/pull/54

**Comment by bsnizek** [comment]
I will give the settings dlg a little more love later ...
