### ISSUE TITLE
Browser can't handle qlr files with several layers defined

### ISSUE THREAD

**Issue by Frederikssund** [Septima/qgis-qlrbrowser#5]
![image](https://cloud.githubusercontent.com/assets/4988513/11502547/c173c9c8-983b-11e5-9835-9cb05420b907.png)

It a double whammer - The tries to raise an error , but the "raise" command result itself in an error

**Comment by Frederikssund** [comment]
The text should have been:

It's a double whammer - The "legend_layersadded" function tries to raise an error, but the "raise" command itself results in an error

/Bo

**Comment by AsgerPetersen** [comment]
It should work with multi layer qlr files. At least with one level of sublayers. 

Does your qlr file by any chance have multiple nested levels? I didnt test that scenario.

![image](https://cloud.githubusercontent.com/assets/1392735/11502662/710507da-983c-11e5-9b7d-ec5bf5c006a0.png)

**Comment by Frederikssund** [comment]
Asger  -

I'll check i the morning...

Regards Bo

Fra: Asger Skovbo Petersen [mailto:notifications@github.com]
Sendt: 1. december 2015 15:02
Til: Septima/qgis-qlrbrowser
Cc: GIS-gruppen (Funktionspostkasse)
Emne: Re: [qgis-qlrbrowser] Browser can't handle qlr files with several layers defined (#5)

It should work with multi layer qlr files. At least with one level of sublayers.

Does your qlr file by any chance have multiple nested levels? I didnt test that scenario.

[image]https://cloud.githubusercontent.com/assets/1392735/11502662/710507da-983c-11e5-9b7d-ec5bf5c006a0.png

##

**Comment by Frederikssund** [comment]
Hi Asger - 
- Scenario 1: A qlr file that show several layers _nested_ in a group: This works witout a hitch.
- Scenario 2: a qlr file that shows 2 layers - _not_ nested in a group. This results in the above mentioned python error, _but_ the layers are shown correctly. (Sorry about my erroneous error-report :-)
- Scenario 3: a qlr file that shows several layers nested in two groups: This results in the same error, but all the layers are shown correctly.

It seems like the only problem is that you try to raise a "Yikes" (??)  exception with a wrong type of argument

**Comment by Frederikssund** [comment]
If you change the "If blah blah blah: Raise ("Yikes")" to something like this:

```
        assert (indexFrom == indexTo), "Yikes !! NOT indexFrom == indexTo"
```

It still barfs in the code, but at least it will complain about the actual error, not the raise command

**Comment by AsgerPetersen** [comment]
Yikes! This a bit embarrasing. I am glad you made it not crash at least.

I honestly didn´t know before that you could make qlr-files with multiple layers _not_ nested in a group (Scenario 2 above), so the code doesn't take ths scenario into account. It will load properly, but sync between the qlr browser and the legend will not work.

I am going to push a commit which I think fixes these issues.

**Comment by Frederikssund** [comment]
Works as advertised..

Thanks Asger!

/Bo
