### ISSUE TITLE
qlr layers based on shapefiles give a datasource is not valid error

### ISSUE THREAD

**Issue by reginaldc** [Septima/qgis-qlrbrowser#59]
Hi,

After adding several qlr files to the folder I noticed that the files that are based on shapefiles don't work anymore. Also the files that are based on tiffs or sids stopped working. The qlr files that are based on WMS or database connection still work. What could be the cause of this? 
I posted the errormessages in the qgis-user maillist.

Regards,

**Comment by baffioso** [comment]
@reginaldc Try setting your path to absolute in Project Properties (Ctrl+Shift+P) and save the qlr again.
![image](https://cloud.githubusercontent.com/assets/7534153/18340588/1865bca8-75a6-11e6-8d2f-9de34f5430ea.png)

Hope it works

**Comment by reginaldc** [comment]
Hi Anders,

Thanks. That solved it ☺

Regards,

Reginald Carlier
Deskundige GIS

[http://www.ingelmunster.be/ingelmunster.gif]

Gemeente Ingelmunster, Oostrozebekestraat 4, 8770 Ingelmunster
T +32 51 33 74 39 www.ingelmunster.behttp://www.ingelmunster.be

[http://www.ingelmunster.be/fb.jpg]https://www.facebook.com/Ingelmunster/ [http://www.ingelmunster.be/go.jpg] https://plus.google.com/+ingelmunster  [http://www.ingelmunster.be/in.jpg] https://www.instagram.com/ingelmunster/  [http://www.ingelmunster.be/pi.jpg] https://www.pinterest.com/ingelmunster/  [http://www.ingelmunster.be/tw.jpg] https://twitter.com/ingelmunster
Van: Anders Barfod [mailto:notifications@github.com]
Verzonden: donderdag 8 september 2016 9:27
Aan: Septima/qgis-qlrbrowser
CC: Reginald Carlier; Mention
Onderwerp: Re: [Septima/qgis-qlrbrowser] qlr layers based on shapefiles give a datasource is not valid error (#59)

@reginaldchttps://github.com/reginaldc Try setting your path to absolute in Project Properties (Ctrl+Shift+P) and save the qlr again.
[https://cloud.githubusercontent.com/assets/7534153/18340588/1865bca8-75a6-11e6-8d2f-9de34f5430ea.png]https://cloud.githubusercontent.com/assets/7534153/18340588/1865bca8-75a6-11e6-8d2f-9de34f5430ea.png

Hope it works

**Comment by MieWinstrup** [comment]
@baffioso thanks for helping, since it's solved, I will close this issue.
