### ISSUE TITLE
Fail to load multilayer qlr file

### ISSUE THREAD

**Issue by gis-haderslev** [Septima/qgis-qlrbrowser#61]
When user opens a group of nested layers using qlr-browser:
1.) group-layer appears in Layers Panel but are not drawn
2.) casts Error and close QGIS on 'Remove layer' or 'Zoom to layer'

**Comment by Frederikssund** [comment]
It might be a special case of #59 or #60. There is workaround for #59 and #60 is a general problem for Qgis, i.e not specific for Qlr-Browser.

Is it all your qlr files - that contains layergroups - that behaves likewise ?

**Comment by dikkri** [comment]
Our problem was like this:
Qlr files that are based on shapefiles didn't work. Also the files that are based on tiffs stopped working. The qlr files that are based on WMS or database connection still work.

Setting the path to absolute in Project Properties (Ctrl+Shift+P) and saving the qlr again solved the problem.
I will close this issue.
