### ISSUE TITLE
QGIS 2.18.15 error - layers not loading

### ISSUE THREAD

**Issue by Jakob-Lanstorp** [Septima/qgis-qlrbrowser#62]
It seems like the Qlr Browser is not working with the latest QGIS 2.18.15 (downloaded Dec 14th 2017). The layers do not load when checked. The is no log message for diagnostic in the log message panel.

**Comment by MieWinstrup** [comment]
@Jakob-Lanstorp, thanks for reporting the problem.
I have the same problem.

**Comment by ArtificialTruth** [comment]
I can confirm this issue.
Running Windows 7 Enterprise 32bit.

| QGIS-version             | 2.18.15          | QGIS-koderevision  | ac2d111ed1             |
|--------------------------|------------------|--------------------|------------------------|
| Kompileret mod Qt        | 4.8.6            | Kører mod Qt       | 4.8.6                  |
| Kompileret mod GDAL/OGR  | 2.2.3            | Kører mod GDAL/OGR | 2.2.3                  |
| Kompileret mod GEOS      | 3.5.0-CAPI-1.9.0 | Kører mod GEOS     | 3.5.0-CAPI-1.9.0 r4084 |
| PostgreSQL-klientversion | 9.5.3            | SpatiaLite-version | 4.3.0                  |
| QWT-version              | 6.0.2            | PROJ.4-version     | 493                    |
| QScintilla2-version      | 2.8.4            |                    |                        |

**Comment by danielarnason** [comment]
Er der noget nyt angående det her issue?

Jeg oplever det samme i QGIS 2.18.16

**Comment by gis-haderslev** [comment]
We have the same problem in QGIS 2.18.16

**Comment by MieWinstrup** [comment]
Der er sket mange ændringer fra QGIS 2.18.14 til QGIS 2.18.15. Vi går igang med at undersøge hvorfor man ikke længere kan tilføje lag fra qlr-browseren. I får besked om hvad vi finder ud af.

**Comment by ArtificialTruth** [comment]
Appriciate it Mie!

**Comment by MieWinstrup** [comment]
A new version of the plugin (1.0.0) have been uploaded to the QGIS Plugin Repository for approval.
