### ISSUE TITLE
Plugin migration to QGIS 3

### ISSUE THREAD

**Issue by baffioso** [Septima/qgis-qlrbrowser#66]
Have there been done any work on migrating QLR-browser to a QGIS3 plugin? Ballerup Kommune could be interested initializing this.

**Comment by MieWinstrup** [comment]
We haven't looked into migrating the QLR-browser yet.

I'm wondering if it would be an idea to have an online meeting about the migration to QGIS3 and discussing if there are additions or changes to the QLR-browser, that should be implemented with the new version, such as:

**Improvements:**
- Improving speed (#31)

**Bug fixes**
- Solving the bug with displayed filtered layers (#58 )

**New features**
- Have a second root for qlr-files (#44 )
- Order of added layers (#64 )

**Comment by gis-haderslev** [comment]
Haderslev Kommune is also interested in QLR-browser as a QGIS3 plugin.

**Comment by MieWinstrup** [comment]
Til orientering til andre, der følger denne tråd:
Vi holder et onlinemøde om konvertering af QLR-browseren til QGIS 3 i morgen kl 11. Skriv til mig (mie@septima.dk) hvis I er interesseret i at deltage i mødet.

**Comment by MieWinstrup** [comment]
The plugin is upgraded to QGIS 3, and released to QGIS Official Plugin Repository as version 2.0.1 (f1f1f0f). Issue is closed.

**Comment by baffioso** [comment]
Nice
