### ISSUE TITLE
More descriptive dialog when a layer from the qlr-browser is added

### ISSUE THREAD

**Issue by MieWinstrup** [Septima/qgis-qlrbrowser#70]
The current dialog when a layer is added from the qlr-browser to the layer panel:
![image](https://user-images.githubusercontent.com/16276034/41648875-63d1bef6-747a-11e8-9131-0b1ddc1ef234.png)

It would be more descriptive if the text in the dialog was something like:
'Qlr-browser: Adding qlr-file to the layer panel '
And in the Danish version: 'Qlr-browser: Tilføjer qlr-fil til lagpanelet'

**Comment by klavspc** [comment]
Translation TBD
