### ISSUE TITLE
Settings dialogue of qlr-browser is missing in QGIS 3.2

### ISSUE THREAD

**Issue by reginaldc** [Septima/qgis-qlrbrowser#74]
Hi,

Thanks for this usefull plugin. I used it a lot in QGIS 2.18.
When I installed it in QGIS 3.2 I didn't find the settings dialogue. Where can I set the root folder of the qlr-browser?

Regards,

**Comment by reginaldc** [comment]
Some additional information:
This is the error when I click in the file-browser:

QlrBrowser\ui\dockwidget.py", line 161, in _treeitem_doubleclicked
              if item.fileitem.isdir:
             AttributeError: 'QTreeWidgetItem' object has no attribute 'fileitem'

**Comment by reginaldc** [comment]
Update

I found the place where the settings are integrated. 
Nice to have them in the options panel

:+1:

**Comment by MieWinstrup** [comment]
Good to hear that you like the plugin - and found the settingsdialog. 
I assume it solved your problem - and I can close this issue?

**Comment by reginaldc** [comment]
Indeed, 

Regards,
