### ISSUE TITLE
qlr of geopackage is not showing

### ISSUE THREAD

**Issue by reginaldc** [Septima/qgis-qlrbrowser#76]
Hi,

I noticed that qlr files generated from geopackages fail in the qlrbrowser.

<layer-tree-layer id="Cadmap_Kadastrale_Gebouwen_2018_55e1d77c_eb62_4598_9802_6c20f5ed92b7" checked="Qt::Checked" source="/srvgis/data/data/Gis/Cadmap/2018/Cadmap2018.gpkg|layername=Cadmap_Kadastrale_Gebouwen_2018" providerKey="ogr" expanded="1" name="Cadmap_Kadastrale_Gebouwen_2018">

This is my source definition. When replacing this source with a shapefile it works. I guesss the "|" character is not recognised?

Could anyone confirm this?

Regards,

**Comment by MieWinstrup** [comment]
It works fine for me - as long as I create the qlr-file with QGIS 2.18

**Comment by reginaldc** [comment]
I can confirm that it works with QGIS 2.18.
In the attached zip you can see what QGIS 3.4.2 makes with the same data and also with absolute paths.
[qlr.zip](https://github.com/Septima/qgis-qlrbrowser/files/2652090/qlr.zip)

Regards,

**Comment by bvthomsen** [comment]
Just in case anybody is interested: QLR Browser works with QGIS ver 3.22 regarding GeoPackage based layers. I suggest, you close this issue
