### ISSUE TITLE
Problems wih relative path in .qlr-files (bug?)

### ISSUE THREAD

**Issue by ghost** [Septima/qgis-qlrbrowser#77]
Hi
I'm testing the qlr-browser in QGIS 3.6 (OSGeo4W-dist on a Windows 10 64 bit machine), and it seems like qlr-browser is having problems with relative paths in the qlr-files. If the layer (a shp-file) is located in the same drive as the qlr-browser root-path, and I'm saving the layer as a qlr-file, QGIS uses a relative paths in the qlr-file. And when I try to open this qlr-file with qlr-browser, the layer opens, but without any geometry objects. If I edit the qlr-file manually, and set the path as an absolute path, then qlr-browser can open the layer with geometry-objects.

**Comment by AsgerPetersen** [comment]
Hi @koetter 

Absolute paths has always been a requirement for the qlr-browser to work. 

We MAY be able to rewrite the plugin to function with relative paths, but that is not on the road map at the moment. We will gladly estimate the cost for an investigation and possibly a fix.
