### ISSUE TITLE
QlrBrowers is very slow

### ISSUE THREAD

**Issue by Jakob-Lanstorp** [Septima/qgis-qlrbrowser#81]
Not sure if this is related to https://github.com/Septima/qgis-qlrbrowser/issues/27.

We have a very large root folder, making the QlrBrowser active will freeze QGIS for several minutes. If you by mistake leave the QlrBrowser in front or visual active and closes QGIS, next start up of QGIS will take many minutes. If you don't have the QlrBrowser tab in front but say Layers or Browser tab in front (visual) QGIS opens from scratch in a short time.

This has gotten even worse now many people work from home over a VPN connection.

**Comment by AsgerPetersen** [comment]
Hi @Jakob-Lanstorp 

Thank you for your report.

It sounds like it is basically the same issue as #27 with a fix described in #31

If you are interested in discussing a fix please get in contact with @MieWinstrup

**Comment by MieWinstrup** [comment]
Async load implemented in [version 3.0.0](https://github.com/Septima/qgis-qlrbrowser/releases/tag/v.3.0.0)
