### ISSUE TITLE
Add message when qlr-browser is loading

### ISSUE THREAD

**Issue by MieWinstrup** [Septima/qgis-qlrbrowser#89]
Add a message when the qlr-browser is loading the files

**Comment by klavspc** [comment]
Den skriver allerede nu _Loading..._ mens den loader

Send gerne screen shot (og kopi af qlr-mappen), hvor den ikke gør det

**Comment by klavspc** [comment]
Prøv at trykke "Reload" så kan du se det (og samtidig se hvor lang tid det tager at loade)
