### ISSUE TITLE
Double click may load layers double 

### ISSUE THREAD

**Issue by AsgerPetersen** [Septima/qgis-qlrbrowser#9]
Double klik on check box results in double layer load.

**Comment by AsgerPetersen** [comment]
Also happens with a standard mouse

**Comment by AsgerPetersen** [comment]
Grr. I can't reproduce. @MieWinstrup can you?

**Comment by MieWinstrup** [comment]
@AsgerPetersen : I'll take a look at it.

**Comment by MieWinstrup** [comment]
@AsgerPetersen : I can sometimes reproduce the bug if I dobbleclick on a WMS layer in the Qlr Browser while it is loading.

**Comment by AsgerPetersen** [comment]
Ok. So double clicking a slow loading item may load the content twice and loose the connection between the loaded layers and the qlr-browser.

The root cause is that when we ask QGIS to load a qlr file, it doesn't give us a handle to what it loaded. [See this line](https://github.com/Septima/qgis-qlrbrowser/blob/87b290772fb5e5175bcb788ccd7c9099a496e512/src/QlrBrowser/core/qlrmanager.py#L127).

This means that we have to listen to all layers being loaded into QGIS and the figure out if we loaded the layer and what qlr it came from! [See this function](https://github.com/Septima/qgis-qlrbrowser/blob/87b290772fb5e5175bcb788ccd7c9099a496e512/src/QlrBrowser/core/qlrmanager.py#L72-L93)

Fixing this is rather difficult. We could maybe block events from the browser while we are loading.

**Comment by AsgerPetersen** [comment]
@Frederikssund @gis-haderslev What to do about this? As I see it we have three possible solutions:
- Leave it as it is
- Disable double clicking
- Try to implement code which allows double clicking, but disallows fast consecutive double clicks

**Comment by Frederikssund** [comment]
If it's going to take a significant amount of time to sove it, I would suggest that we disable the doubleclick function for now. Not because of the money involved, but for finishing this part of the project as fast as possible. We can always return and solve this problem a later stage.

**Comment by gis-haderslev** [comment]
Disable double click
